#!/usr/bin/env bash
#
#  ||''.   ^   ||''. \\ /' ||''. ||  | //''\
#  ||--'  //\  ||--'   V   ||-+' ||  | ``--.
#  ||    //''\ ||     .|   ||  \ `\__' \\__/
#
# Description:              Another ascii generator
# Dependencies:             none
# Optionnal dependencies:   none
# Author:                   gawlk
# Contributors:             none

# ---
# LOCAL
# ---

papyrus.a() {
    #
    #   ^
    #  //\
    # //''\
    #
    local line0="   ^  "
    local line1="  //\\ "
    local line2=" //''\\"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.b() {
    #
    # ||''\
    # ||--<
    # ||__/
    #
    local line0=" ||''\\"
    local line1=" ||--<"
    local line2=" ||__/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.c() {
    #
    #  //'.
    # ||   
    #  \\_/
    #
    local line0="  //'."
    local line1=" ||   "
    local line2="  \\\\_/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.d() {
    #
    # ||'\
    # ||  |
    # ||_/
    #
    local line0=" ||'\\ "
    local line1=" ||  |"
    local line2=" ||_/ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.e() {
    #
    # ||''|
    # ||-
    # ||__|
    #
    local line0=" ||''|"
    local line1=" ||-  "
    local line2=" ||__|"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.f() {
    #
    # ||''|
    # ||-
    # ||
    #
    local line0=" ||''|"
    local line1=" ||-  "
    local line2=" ||   "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.g() {
    #
    #  //'|
    # ||  _
    #  \\_/
    #
    local line0="  //'|"
    local line1=" ||  _"
    local line2="  \\\\_/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.h() {
    #
    # ||  |
    # ||--|
    # ||  |
    #
    local line0=" ||  |"
    local line1=" ||--|"
    local line2=" ||  |"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.i() {
    #
    # '||'
    #  ||
    # .||.
    #
    local line0=" '||' "
    local line1="  ||  "
    local line2=" .||. "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.j() {
    #
    # |''|'
    #    |
    # \\_/
    #
    local line0=" |''|'"
    local line1="    | "
    local line2=" \\\\_/ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.k() {
    #
    #  || /
    #  ||x
    # .|| \
    #
    local line0="  || /"
    local line1="  ||x "
    local line2=" .|| \\"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.l() {
    #
    # '||  
    #  || 
    #  ||_|
    #
    local line0=" '||  "
    local line1="  ||  "
    local line2="  ||_|"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.m() {
    #
    # ||\/|
    # ||  |
    # ||  |
    #
    local line0=" ||\\/|"
    local line1=" ||  |"
    local line2=" ||  |"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.n() {
    #
    # |\  |
    # ||\ |
    # || \|
    #
    local line0=" |\\  |"
    local line1=" ||\\ |"
    local line2=" || \\|"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.o() {
    #
    #  //\ 
    # ||  |
    #  \\/
    #
    local line0="  //\\ "
    local line1=" ||  |"
    local line2="  \\\\/ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.p() {
    #
    # ||''.
    # ||--'
    # ||
    #
    local line0=" ||''."
    local line1=" ||--'"
    local line2=" ||   "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.q() {
    #
    #  //\ 
    # ||  |
    #  \\X_
    #
    local line0="  //\\ "
    local line1=" ||  |"
    local line2="  \\\\X_"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.r() {
    #
    # ||''.
    # ||-+'
    # ||  \
    #
    local line0=" ||''."
    local line1=" ||-+'"
    local line2=" ||  \\"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.s() {
    #
    # //''\
    # ``--.
    # \\__/
    #
    local line0=" //''\\"
    local line1=" \`\`--."
    local line2=" \\\\__/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.t() {
    #
    # ['|']
    #   |
    #  .|
    #
    local line0=" ['|']"
    local line1="   |  "
    local line2="  .|  "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.u() {
    #
    # ||  |
    # ||  |
    # `\__'
    #
    local line0=" ||  |"
    local line1=" ||  |"
    local line2=" \`\\__'"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.v() {
    #
    # \\  /
    #  \\/
    #   V
    #
    local line0=" \\\\  /"
    local line1="  \\\\/ "
    local line2="   V  "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.w() {
    #
    # ||  |
    # ||  |
    # ||/\|
    #
    local line0=" ||  |"
    local line1=" ||  |"
    local line2=" ||/\\|"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.x() {
    #
    # '\ //
    #   X/
    # _//\_
    #
    local line0=" '\\ //"
    local line1="   X/ "
    local line2=" _//\\_"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.y() {
    #
    # \\ /'
    #   V
    #  .|
    #
    local line0=" \\\\ /'"
    local line1="   V  "
    local line2="  .|  "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.z() {
    #
    # ''//
    #  //
    # //__.
    #
    local line0=" ''// "
    local line1="  //  "
    local line2=" //__."
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.0() {
    #
    #  //\ 
    # ||//|
    #  \\/
    #
    local line0="  //\\ "
    local line1=" ||//|"
    local line2="  \\\\/ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.1() {
    #
    # /||
    #  ||
    # _||_
    #
    local line0=" /||  "
    local line1="  ||  "
    local line2=" _||_ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.2() {
    #
    #  /'X\
    # ` //
    #  //__
    #
    local line0=" /'X\\ "
    local line1="  //  "
    local line2=" //__ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.3() {
    #
    # //''\
    #    -<
    # \\__/
    #
    local line0=" //''\\"
    local line1="    -<"
    local line2=" \\\\__/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.4() {
    #
    #  //|
    # //_|_
    #   ||
    #
    local line0="  //| "
    local line1=" //_|_"
    local line2="   || "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.5() {
    #
    # ||'''
    # `'--.
    # \\__/
    #
    local line0=" ||'''"
    local line1=" \`'--."
    local line2=" \\\\__/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.6() {
    #
    #  //''
    # ||--.
    #  \\_/
    #
    local line0="  //''"
    local line1=" ||--."
    local line2="  \\\\_/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.7() {
    #
    # \''//
    #   //
    #  //
    #
    local line0=" \\''//"
    local line1="   // "
    local line2="  //  "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.8() {
    #
    # //''\
    # >>--<
    # \\__/
    #
    local line0=" //''\\"
    local line1=" >>--<"
    local line2=" \\\\__/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.9() {
    #
    # //''|
    # ``--|
    # \\__|
    #
    local line0=" //''|"
    local line1=" \`\`--|"
    local line2=" \\\\__|"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.comma() {
    #
    #
    #
    # ')
    #
    local line0="   "
    local line1="   "
    local line2=" ')"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.dot() {
    #
    #
    #
    # o
    #
    local line0="   "
    local line1="   "
    local line2=" o "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.semicolon() {
    #
    #
    #  o
    # ')
    #
    local line0="   "
    local line1="  o"
    local line2=" ')"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.colon() {
    #
    #
    # o
    # o
    #
    local line0="   "
    local line1=" o "
    local line2=" o "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.interrogation() {
    #
    # '')
    #  '
    #  o
    #
    local line0=" '')"
    local line1="  ' "
    local line2="  o "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.quote() {
    #
    #  |
    #  '
    #
    #
    local line0=" |"
    local line1=" '"
    local line2="  "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.double_quote() {
    #
    #  | |
    #  ' '
    #
    #
    local line0=" | |"
    local line1=" ' '"
    local line2="    "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.grave() {
    #
    #  \
    #   '
    #
    #
    local line0=" \\ "
    local line1="  '"
    local line2="   "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.left_chevron() {
    #
    #  //
    # <<
    #  \\
    #
    local line0="  //"
    local line1=" << "
    local line2="  \\\\"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.right_chevron() {
    #
    # \
    #  >
    # /
    #
    local line0=" \\  "
    local line1="  > "
    local line2=" /  "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.slash() {
    #
    #   //
    #  //
    # //
    #
    local line0="   //"
    local line1="  // "
    local line2=" //  "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.backslash() {
    #
    # \
    #  \
    #   \
    #
    local line0=" \\   "
    local line1="  \\  "
    local line2="   \\ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.bar() {
    #
    # |
    # |
    # |
    #
    local line0=" | "
    local line1=" | "
    local line2=" | "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.tild() {
    #
    #
    # //\//
    #  
    #
    local line0="      "
    local line1=" //\\//"
    local line2="      "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.excalamation() {
    #  
    # |
    # '
    # o
    #
    local line0=" | "
    local line1=" ' "
    local line2=" o "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.at() {
    #  
    #  //'\
    # || d/
    #  \\__
    #
    local line0="  //'\\"
    local line1=" || d/"
    local line2="  \\\\__"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.hash() {
    #  
    # ++-+
    # || |
    # ++-+
    #
    local line0=" ++-+ "
    local line1=" || | "
    local line2=" ++-+ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.dollar() {
    #
    # //||\
    # ``||.
    # \\||/
    #
    local line0=" //||\\"
    local line1=" \`\`||."
    local line2=" \\\\||/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.percentage() {
    #  
    # o //
    #  //
    # // o
    #
    local line0=" o // "
    local line1="  //  "
    local line2=" // o "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.circumflex() {
    #  
    #   ^
    #  //\
    #
    #
    local line0="  ^  "
    local line1=" //\\ "
    local line2="     "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.ampersand() {
    #
    # //''
    # >>--+
    # \\__l
    #
    local line0=" //'' "
    local line1=" >>--+"
    local line2=" \\\\__l"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.asterix() {
    #
    # \ //
    # -X/_
    # //\.
    #
    local line0=" \\ //"
    local line1=" -X/-"
    local line2=" //\\."
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.minus() {
    #  
    #
    # ---
    #
    #
    local line0="     "
    local line1=" --- "
    local line2="     "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.equal() {
    #  
    #
    # ===
    #
    #
    local line0="     "
    local line1=" === "
    local line2="     "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.underscore() {
    #  
    #
    # 
    # ---
    #
    local line0="     "
    local line1="     "
    local line2=" ___ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.plus() {
    #  
    #  ..
    # -++-
    #  ''
    #
    local line0="  .. "
    local line1=" -++-"
    local line2="  '' "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.left_parenthese() {
    #  
    #  /
    # ||
    #  \
    #
    local line0="  / "
    local line1=" || "
    local line2="  \\ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.right_parenthese() {
    #  
    # \
    # ||
    # /
    #
    local line0=" \\  "
    local line1=" || "
    local line2=" /  "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.left_bracket() {
    #  
    # ||''
    # ||
    # ||__
    #
    local line0=" ||''"
    local line1=" ||  "
    local line2=" ||__"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.right_bracket() {
    #  
    # ''||
    #   ||
    # __||
    #
    local line0=" ''||"
    local line1="   ||"
    local line2=" __||"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.left_braces() {
    #  
    #  //'
    # <<
    #  \\_
    #
    local line0="  //'"
    local line1=" <<  "
    local line2="  \\\\_"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

papyrus.right_braces() {
    #  
    # '\\
    #   >>
    # _//
    #
    local line0=" '\\\\ "
    local line1="   >>"
    local line2=" _// "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# MAIN
# ---

papyrus.main() {
    local string="$( printf '%s\n' "${1,,}" )"
    local char
    local ascii
    local oldIFS=$IFS
    IFS=$'\n'

    if [[ -n "$string" ]]
    then
        for (( i=0; i < ${#string}; i++ ))
        do
            char="${string:$i:1}"

            case "$char" in
                [a-z] | [0-9] ) ascii=( $( papyrus."$char" ) ) ;;
                ","  ) ascii=( $( papyrus.comma ) ) ;;
                "."  ) ascii=( $( papyrus.dot ) ) ;;
                ";"  ) ascii=( $( papyrus.semicolon ) ) ;;
                ":"  ) ascii=( $( papyrus.colon ) ) ;;
                "?"  ) ascii=( $( papyrus.interrogation ) ) ;;
                "'"  ) ascii=( $( papyrus.quote ) ) ;;
                "\"" ) ascii=( $( papyrus.double_quote ) ) ;;
                "\`" ) ascii=( $( papyrus.grave ) ) ;;
                "<"  ) ascii=( $( papyrus.left_chevron ) ) ;;
                ">"  ) ascii=( $( papyrus.right_chevron ) ) ;;
                "/"  ) ascii=( $( papyrus.slash ) ) ;;
                "\\" ) ascii=( $( papyrus.backslash ) ) ;;
                "|"  ) ascii=( $( papyrus.bar ) ) ;;
                "~"  ) ascii=( $( papyrus.tild ) ) ;;
                "!"  ) ascii=( $( papyrus.excalamation ) ) ;;
                "@"  ) ascii=( $( papyrus.at ) ) ;;
                "#"  ) ascii=( $( papyrus.hash ) ) ;;
                "$"  ) ascii=( $( papyrus.dollar ) ) ;;
                "%"  ) ascii=( $( papyrus.percentage ) ) ;;
                "^"  ) ascii=( $( papyrus.circumflex ) ) ;;
                "&"  ) ascii=( $( papyrus.ampersand ) ) ;;
                "*"  ) ascii=( $( papyrus.asterix ) ) ;;
                "-"  ) ascii=( $( papyrus.minus ) ) ;;
                "="  ) ascii=( $( papyrus.equal ) ) ;;
                "_"  ) ascii=( $( papyrus.underscore ) ) ;;
                "+"  ) ascii=( $( papyrus.plus ) ) ;;
                "("  ) ascii=( $( papyrus.left_parenthese ) ) ;;
                ")"  ) ascii=( $( papyrus.right_parenthese ) ) ;;
                "["  ) ascii=( $( papyrus.left_bracket ) ) ;;
                "]"  ) ascii=( $( papyrus.right_bracket ) ) ;;
                "{"  ) ascii=( $( papyrus.left_braces ) ) ;;
                "}"  ) ascii=( $( papyrus.right_braces ) ) ;;
                " "  ) ascii=( "    " "    " "    " ) ;;
            esac

            line0+="${ascii[0]}"
            line1+="${ascii[1]}"
            line2+="${ascii[2]}"
        done

        printf '\n %s\n %s\n %s\n\n' "$line0" "$line1" "$line2"
    else
        papyrus papyrus
        printf '%s\n\n' 'Write something after "papyrus" to have a different text !'
    fi

    IFS=$oldIFS
}

# ---
# LAUNCH
# ---

papyrus.main "$*"
