#!/bin/bash

batt=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/percentage:/{print $2}')

state=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/state:/{print $2}')

if [ "${state}" == "charging" ]
then
	t="%{B#00ff00} * %{B#75ffffff}"
else
	t="%{B#ffa500} ! %{B#75ffffff}"
fi

echo "$t $batt"
