cursor:
  style:
    shape: Block

font:
  size: 10.45

  normal:
    family: CozetteVector

window:
  padding:
    x: 12
    y: 12

colors:
  primary:
    background: '#ffffea'
    foreground: '#000000'

  cursor:
    cursor: '#000000'
    text: '#ffffea'


  bright:
    black: '#5e5252'
    blue: '#426a79'
    cyan: '#989a9c'
    green: '#858162'
    magenta: '#97522c'
    red: '#be100e'
    white: '#d5ccba'
    yellow: '#eaa549'
  
  normal:
    black: '#20111b'
    blue: '#426a79'
    cyan: '#989a9c'
    green: '#858162'
    magenta: '#97522c'
    red: '#be100e'
    white: '#968c83'
    yellow: '#eaa549'

cursor:
    style: Beam
    thickness: 0.25
