font:
  size: 10

  normal:
    family: CozetteVector

window:
  padding:
    x: 12
    y: 12

colors:
  primary:
    background: '#ffffea'
    foreground: '#000000'

  normal:
    black: '#282828'
    red: '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'
  
  bright:
    black:   '#928374'
    red:     '#fb4934'					         
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

  cursor:
    cursor: '#990000'
    text: '#ffffff'

cursor:
  style: Beam
  thickness: 0.35
