#!/bin/bash


berryc border_width       3
berryc inner_border_width 0
berryc top_gap            0

berryc focus_color         ffffff
berryc unfocus_color       bebebe
berryc inner_focus_color  cdcdcd
berryc inner_unfocus_color cdcdcd
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

berryc smart_place "true"
berryc draw_text   "false"
berryc title_height 20
berryc edge_lock   "false"
berryc set_font    "t cherry"
