#!/bin/bash


berryc border_width       3
berryc inner_border_width 0
berryc title_height       0
berryc top_gap            0

berryc focus_color         ffffff
berryc unfocus_color       bebebe
berryc inner_focus_color  2f4f4f
berryc inner_unfocus_color 2f4f4f
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

berryc smart_place "true"
berryc draw_text   "false"
berryc edge_lock   "false"
berryc set_font    "t cherry"
