#!/bin/sh

command="chocolate-doom -window -iwad"

printf "1: Ultimate DOOM\n2: DOOM II\n\n"

read -sn1

if [ "$REPLY" = "1" ]; then
	$command ~/games/DOOM.WAD &
elif [ "$REPLY" = "2" ]; then
	$command ~/games/DOOM2.WAD &
else
	printf "Invalid selection!\n" 1>&2 
fi
