#!/bin/sh

cp ~/.vimrc ~/repos/rice/.vimrc
cp ~/.bashrc ~/repos/rice/.bashrc
cp ~/.xinitrc ~/repos/rice/.xinitrc
cp ~/.alacritty.yml ~/repos/rice/.alacritty.yml  

cp -r ~/.scripts ~/repos/rice
cp -r ~/.xmonad ~/repos/rice
cp -r ~/.config/picom ~/repos/rice/.config
cp -r ~/.config/sxhkd ~/repos/rice/.config 
cp -r ~/.merlin ~/repos/rice

cp ~/.Xresources ~/repos/rice/.Xresources

